/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controle.ProdutoControle;
import Modelo.Produto;
import com.itextpdf.io.font.FontConstants;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Junim Roberti
 */
public class JfrmRelatorioProduto extends javax.swing.JFrame {

    /**
     * Creates new form JfrmRelatorioProduto
     */
    public JfrmRelatorioProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtxtFornecedor = new javax.swing.JTextField();
        jbtnGerarRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Relatório Produto");

        jLabel1.setText("Codigo do Fornecedor:");

        jtxtFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFornecedorActionPerformed(evt);
            }
        });

        jbtnGerarRelatorio.setText("Gerar");
        jbtnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGerarRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jtxtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnGerarRelatorio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnGerarRelatorio)
                    .addComponent(jtxtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFornecedorActionPerformed

    private void jbtnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGerarRelatorioActionPerformed
        // TODO add your handling code here:
        
        ProdutoControle produtoControle = new ProdutoControle();        
        ArrayList<Produto> produtoBuscado = produtoControle.popular();        
        
        try {
            PdfWriter writer = new PdfWriter("RelatorioProduto.pdf");
            PdfDocument pdf = new PdfDocument(writer); 
            Document document = new Document(pdf);
            document.setMargins(20, 20, 20, 20);
            PdfFont font = PdfFontFactory.createFont(FontConstants.TIMES_ROMAN);
            document.setFont(font);
            Paragraph cabecalho1 = new Paragraph("Produtos Cadastrados:"); 
            document.add(cabecalho1);
            Table table = new Table(6);
            table.addCell(new Cell().add(new Paragraph("Codigo")));
            table.addCell(new Cell().add(new Paragraph("Nome do Produto")));
            table.addCell(new Cell().add(new Paragraph("Modelo")));
            table.addCell(new Cell().add(new Paragraph("Data de Validade")));
            table.addCell(new Cell().add(new Paragraph("Preço de Compra")));
            table.addCell(new Cell().add(new Paragraph("Preço de Venda")));
            int x=0;
            for(int i=0; i < produtoBuscado.size(); i++){
                if(Integer.parseInt(jtxtFornecedor.getText()) == produtoBuscado.get(i).getCodigoFornecedor()){
                table.addCell(new Cell().add(new Paragraph(String.valueOf(produtoBuscado.get(i).getCodigo()))));            
                table.addCell(new Cell().add(new Paragraph(produtoBuscado.get(i).getNomeProduto())));
                table.addCell(new Cell().add(new Paragraph(produtoBuscado.get(i).getModelo())));
                table.addCell(new Cell().add(new Paragraph(produtoBuscado.get(i).getDataValidade())));
                table.addCell(new Cell().add(new Paragraph(String.valueOf(produtoBuscado.get(i).getPrecoCompra()))));
                table.addCell(new Cell().add(new Paragraph(String.valueOf(produtoBuscado.get(i).getPrecoVenda()))));  
                x++;
                }                     
            }
            document.add(table); 
            document.close();
            if(x>0){
                Desktop.getDesktop().open(new File("RelatorioProduto.pdf"));
            }else{
                JOptionPane.showMessageDialog(null, "Fornecedor não exite!!");
            }
            } catch (IOException ex) {
            Logger.getLogger(JfrmMenuGerente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnGerarRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmRelatorioProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmRelatorioProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmRelatorioProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmRelatorioProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmRelatorioProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtnGerarRelatorio;
    private javax.swing.JTextField jtxtFornecedor;
    // End of variables declaration//GEN-END:variables
}
