/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controle.EnderecoControle;
import Controle.FuncionarioControle;
import Modelo.Endereco;
import Modelo.Funcionario;
import com.itextpdf.io.font.FontConstants;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Junim Roberti
 */
public class JfrmRelatorioFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form JfrmRelatorioFuncionario
     */
    public JfrmRelatorioFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtTipo = new javax.swing.JTextField();
        jbtnGerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Relatório Funcionário");

        jLabel2.setText("Tipo:");

        jbtnGerar.setText("Gerar");
        jbtnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jtxtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jbtnGerar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnGerar))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGerarActionPerformed
        // TODO add your handling code here:
        FuncionarioControle funcionarioControle = new FuncionarioControle();
        EnderecoControle enderecoControle = new EnderecoControle();
        ArrayList<Funcionario> funcionarioBuscado = funcionarioControle.buscarFuncionario();        
        ArrayList<Endereco> enderecoBuscado = enderecoControle.buscarEndFuncionario(funcionarioBuscado);
        try {
            PdfWriter writer = new PdfWriter("RelatorioFuncionarios.pdf");
            PdfDocument pdf = new PdfDocument(writer); 
            Document document = new Document(pdf);
            document.setMargins(20, 20, 20, 20);
            PdfFont font = PdfFontFactory.createFont(FontConstants.TIMES_ROMAN);
            document.setFont(font);
            Paragraph cabecalho1 = new Paragraph("Funcionários Cadastrados no Sistema:"); 
            document.add(cabecalho1);
            Table table = new Table(7);
            table.addCell(new Cell().add(new Paragraph("Código")));
            table.addCell(new Cell().add(new Paragraph("Tipo")));
            table.addCell(new Cell().add(new Paragraph("Nome")));
            table.addCell(new Cell().add(new Paragraph("Rua")));
            table.addCell(new Cell().add(new Paragraph("Número")));
            table.addCell(new Cell().add(new Paragraph("Bairro")));
            table.addCell(new Cell().add(new Paragraph("Cidade")));
            int x=0;
            for(int i=0; i < funcionarioControle.buscarFuncionario().size(); i++){
                if(Integer.parseInt(jtxtTipo.getText()) == funcionarioControle.buscarFuncionario().get(i).getTipo()){
                    table.addCell(new Cell().add(new Paragraph(String.valueOf(funcionarioControle.buscarFuncionario().get(i).getCodigo()))));
                    table.addCell(new Cell().add(new Paragraph(String.valueOf(funcionarioControle.buscarFuncionario().get(i).getTipo()))));
                    table.addCell(new Cell().add(new Paragraph(funcionarioControle.buscarFuncionario().get(i).getNomeFuncionario())));
                    table.addCell(new Cell().add(new Paragraph(enderecoBuscado.get(i).getRua())));
                    table.addCell(new Cell().add(new Paragraph(enderecoBuscado.get(i).getNumero())));
                    table.addCell(new Cell().add(new Paragraph(enderecoBuscado.get(i).getBairro())));
                    table.addCell(new Cell().add(new Paragraph(enderecoBuscado.get(i).getCidade()))); 
                    x++;
                }
            }
            
            document.add(table);            
            document.close();
            if(x>0){
            Desktop.getDesktop().open(new File("RelatorioFuncionarios.pdf"));
            }else{
                JOptionPane.showMessageDialog(null, "Tipo não exite!!");

            }
            } catch (IOException ex) {
            Logger.getLogger(JfrmMenuGerente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnGerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmRelatorioFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmRelatorioFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmRelatorioFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmRelatorioFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmRelatorioFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtnGerar;
    private javax.swing.JTextField jtxtTipo;
    // End of variables declaration//GEN-END:variables
}
