/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controle.EnderecoControle;
import Controle.FornecedorControle;
import Controle.FuncionarioControle;
import Modelo.Endereco;
import Modelo.Funcionario;
import com.itextpdf.io.font.FontConstants;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.pdf.PdfDocument;
import static com.itextpdf.kernel.pdf.PdfName.Document;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Leticia Ribeiro
 */
public class JfrmMenuGerente extends javax.swing.JFrame {

    /**
     * Creates new form JfrmMenuGerente
     */
    public JfrmMenuGerente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jmnMenu = new javax.swing.JMenuBar();
        jmnAddFuncionario = new javax.swing.JMenu();
        jMenuCadastrarFuncionario = new javax.swing.JMenuItem();
        jMenuExcluirFuncionario = new javax.swing.JMenuItem();
        jMenuBuscarFuncionario = new javax.swing.JMenuItem();
        jMenuAlterarFuncionario = new javax.swing.JMenuItem();
        jmnGerarRelatorio = new javax.swing.JMenu();
        jRelatorioProduto = new javax.swing.JMenuItem();
        jRelatorioFornecedor = new javax.swing.JMenuItem();
        jRelatorioFunciona = new javax.swing.JMenuItem();
        jmnSair = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/manager_icon.png"))); // NOI18N

        jmnAddFuncionario.setText(" Funcionarios");

        jMenuCadastrarFuncionario.setText("Cadastrar Funcionário");
        jMenuCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarFuncionarioActionPerformed(evt);
            }
        });
        jmnAddFuncionario.add(jMenuCadastrarFuncionario);

        jMenuExcluirFuncionario.setText("Remover Funcionário");
        jMenuExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExcluirFuncionarioActionPerformed(evt);
            }
        });
        jmnAddFuncionario.add(jMenuExcluirFuncionario);

        jMenuBuscarFuncionario.setText("Buscar Funcionário");
        jMenuBuscarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBuscarFuncionarioActionPerformed(evt);
            }
        });
        jmnAddFuncionario.add(jMenuBuscarFuncionario);

        jMenuAlterarFuncionario.setText("Alterar Funcionário");
        jMenuAlterarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlterarFuncionarioActionPerformed(evt);
            }
        });
        jmnAddFuncionario.add(jMenuAlterarFuncionario);

        jmnMenu.add(jmnAddFuncionario);

        jmnGerarRelatorio.setText("Relatórios");

        jRelatorioProduto.setText("Gerar Relatório de Produto");
        jRelatorioProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRelatorioProdutoActionPerformed(evt);
            }
        });
        jmnGerarRelatorio.add(jRelatorioProduto);

        jRelatorioFornecedor.setText("Gerar Relatório de Fornecedores");
        jRelatorioFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRelatorioFornecedorActionPerformed(evt);
            }
        });
        jmnGerarRelatorio.add(jRelatorioFornecedor);

        jRelatorioFunciona.setText("Gerar Relatório de Funcionarios");
        jRelatorioFunciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRelatorioFuncionaActionPerformed(evt);
            }
        });
        jmnGerarRelatorio.add(jRelatorioFunciona);

        jmnMenu.add(jmnGerarRelatorio);

        jmnSair.setText("Mais");

        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jmnSair.add(jMenuSair);

        jmnMenu.add(jmnSair);

        setJMenuBar(jmnMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarFuncionarioActionPerformed
        // TODO add your handling code here:
        JfrmCadastrarFuncionario cadastrarFuncionario = new JfrmCadastrarFuncionario();
        cadastrarFuncionario.setLocationRelativeTo(null);
        cadastrarFuncionario.setDefaultCloseOperation(cadastrarFuncionario.DISPOSE_ON_CLOSE);
        cadastrarFuncionario.setVisible(true); 
    }//GEN-LAST:event_jMenuCadastrarFuncionarioActionPerformed

    private void jMenuExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExcluirFuncionarioActionPerformed
        // TODO add your handling code here:
        JfrmRemoverFuncionario excluirFuncionario = new JfrmRemoverFuncionario();
        excluirFuncionario.setLocationRelativeTo(null);
        excluirFuncionario.setDefaultCloseOperation(excluirFuncionario.DISPOSE_ON_CLOSE);
        excluirFuncionario.setVisible(true);                            
    }//GEN-LAST:event_jMenuExcluirFuncionarioActionPerformed

    private void jMenuBuscarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBuscarFuncionarioActionPerformed
        // TODO add your handling code here:
        JfrmBuscarFuncionario buscarFuncionario = new JfrmBuscarFuncionario();
        buscarFuncionario.setLocationRelativeTo(null);
        buscarFuncionario.setDefaultCloseOperation(buscarFuncionario.DISPOSE_ON_CLOSE);
        buscarFuncionario.setVisible(true);
    }//GEN-LAST:event_jMenuBuscarFuncionarioActionPerformed

    private void jMenuAlterarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlterarFuncionarioActionPerformed
        // TODO add your handling code here:
        JfrmAlterarFuncionario alterarFuncionario = new JfrmAlterarFuncionario();
        alterarFuncionario.setLocationRelativeTo(null);
        alterarFuncionario.setDefaultCloseOperation(alterarFuncionario.DISPOSE_ON_CLOSE);
        alterarFuncionario.setVisible(true);
    }//GEN-LAST:event_jMenuAlterarFuncionarioActionPerformed

    private void jRelatorioProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRelatorioProdutoActionPerformed
        // TODO add your handling code here:
        JfrmRelatorioProduto relatorioProduto = new JfrmRelatorioProduto();
        relatorioProduto.setLocationRelativeTo(null);
        relatorioProduto.setDefaultCloseOperation(relatorioProduto.DISPOSE_ON_CLOSE);
        relatorioProduto.setVisible(true);
    }//GEN-LAST:event_jRelatorioProdutoActionPerformed

    private void jRelatorioFuncionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRelatorioFuncionaActionPerformed
        // TODO add your handling code here:
        JfrmRelatorioFuncionario relatorioFuncionario = new JfrmRelatorioFuncionario();
        relatorioFuncionario.setLocationRelativeTo(null);
        relatorioFuncionario.setDefaultCloseOperation(relatorioFuncionario.DISPOSE_ON_CLOSE);
        relatorioFuncionario.setVisible(true);
    }//GEN-LAST:event_jRelatorioFuncionaActionPerformed

    private void jRelatorioFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRelatorioFornecedorActionPerformed
        // TODO add your handling code here:
        JfrmRelatorioFornecedor relatorioFornecedor = new JfrmRelatorioFornecedor();
        relatorioFornecedor.setLocationRelativeTo(null);
        relatorioFornecedor.setDefaultCloseOperation(relatorioFornecedor.DISPOSE_ON_CLOSE);
        relatorioFornecedor.setVisible(true);

    }//GEN-LAST:event_jRelatorioFornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmMenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmMenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmMenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmMenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmMenuGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuAlterarFuncionario;
    private javax.swing.JMenuItem jMenuBuscarFuncionario;
    private javax.swing.JMenuItem jMenuCadastrarFuncionario;
    private javax.swing.JMenuItem jMenuExcluirFuncionario;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JMenuItem jRelatorioFornecedor;
    private javax.swing.JMenuItem jRelatorioFunciona;
    private javax.swing.JMenuItem jRelatorioProduto;
    private javax.swing.JMenu jmnAddFuncionario;
    private javax.swing.JMenu jmnGerarRelatorio;
    private javax.swing.JMenuBar jmnMenu;
    private javax.swing.JMenu jmnSair;
    // End of variables declaration//GEN-END:variables
}
