/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controle.EnderecoControle;
import Controle.FornecedorControle;
import Modelo.Endereco;
import com.itextpdf.io.font.FontConstants;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.pdf.PdfDocument;
import static com.itextpdf.kernel.pdf.PdfName.Document;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Leticia Ribeiro
 */
public class JfrmMenuGerente extends javax.swing.JFrame {

    /**
     * Creates new form JfrmMenuGerente
     */
    public JfrmMenuGerente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jmnMenu = new javax.swing.JMenuBar();
        jmnAddFuncionario = new javax.swing.JMenu();
        jMenuCadastrarFuncionario = new javax.swing.JMenuItem();
        jMenuExcluirFuncionario = new javax.swing.JMenuItem();
        jMenuBuscarFuncionario = new javax.swing.JMenuItem();
        jMenuAlterarFuncionario = new javax.swing.JMenuItem();
        jmnGerarRelatorio = new javax.swing.JMenu();
        jMenuGerarRelatorio = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmnSair = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/manager_icon.png"))); // NOI18N

        jmnAddFuncionario.setText(" Funcionarios");

        jMenuCadastrarFuncionario.setText("Cadastrar Funcionário");
        jMenuCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarFuncionarioActionPerformed(evt);
            }
        });
        jmnAddFuncionario.add(jMenuCadastrarFuncionario);

        jMenuExcluirFuncionario.setText("Remover Funcionário");
        jMenuExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExcluirFuncionarioActionPerformed(evt);
            }
        });
        jmnAddFuncionario.add(jMenuExcluirFuncionario);

        jMenuBuscarFuncionario.setText("Buscar Funcionário");
        jMenuBuscarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBuscarFuncionarioActionPerformed(evt);
            }
        });
        jmnAddFuncionario.add(jMenuBuscarFuncionario);

        jMenuAlterarFuncionario.setText("Alterar Funcionário");
        jMenuAlterarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlterarFuncionarioActionPerformed(evt);
            }
        });
        jmnAddFuncionario.add(jMenuAlterarFuncionario);

        jmnMenu.add(jmnAddFuncionario);

        jmnGerarRelatorio.setText("Relatórios");

        jMenuGerarRelatorio.setText("Gerar Relatório de Produto");
        jMenuGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGerarRelatorioActionPerformed(evt);
            }
        });
        jmnGerarRelatorio.add(jMenuGerarRelatorio);

        jMenuItem1.setText("Gerar Relatório de Fornecedores");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmnGerarRelatorio.add(jMenuItem1);

        jMenuItem2.setText("Gerar Relatório de Funcionarios");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmnGerarRelatorio.add(jMenuItem2);

        jmnMenu.add(jmnGerarRelatorio);

        jmnSair.setText("Mais");

        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jmnSair.add(jMenuSair);

        jmnMenu.add(jmnSair);

        setJMenuBar(jmnMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarFuncionarioActionPerformed
        // TODO add your handling code here:
        JfrmCadastrarFuncionario cadastrarFuncionario = new JfrmCadastrarFuncionario();
        cadastrarFuncionario.setLocationRelativeTo(null);
        cadastrarFuncionario.setDefaultCloseOperation(cadastrarFuncionario.DISPOSE_ON_CLOSE);
        cadastrarFuncionario.setVisible(true); 
    }//GEN-LAST:event_jMenuCadastrarFuncionarioActionPerformed

    private void jMenuExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExcluirFuncionarioActionPerformed
        // TODO add your handling code here:
        JfrmRemoverFuncionario excluirFuncionario = new JfrmRemoverFuncionario();
        excluirFuncionario.setLocationRelativeTo(null);
        excluirFuncionario.setDefaultCloseOperation(excluirFuncionario.DISPOSE_ON_CLOSE);
        excluirFuncionario.setVisible(true);                            
    }//GEN-LAST:event_jMenuExcluirFuncionarioActionPerformed

    private void jMenuBuscarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBuscarFuncionarioActionPerformed
        // TODO add your handling code here:
        JfrmBuscarFuncionario buscarFuncionario = new JfrmBuscarFuncionario();
        buscarFuncionario.setLocationRelativeTo(null);
        buscarFuncionario.setDefaultCloseOperation(buscarFuncionario.DISPOSE_ON_CLOSE);
        buscarFuncionario.setVisible(true);
    }//GEN-LAST:event_jMenuBuscarFuncionarioActionPerformed

    private void jMenuAlterarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlterarFuncionarioActionPerformed
        // TODO add your handling code here:
        JfrmAlterarFuncionario alterarFuncionario = new JfrmAlterarFuncionario();
        alterarFuncionario.setLocationRelativeTo(null);
        alterarFuncionario.setDefaultCloseOperation(alterarFuncionario.DISPOSE_ON_CLOSE);
        alterarFuncionario.setVisible(true);
    }//GEN-LAST:event_jMenuAlterarFuncionarioActionPerformed

    private void jMenuGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGerarRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuGerarRelatorioActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try {
            FornecedorControle fornecedor = new FornecedorControle();
            EnderecoControle endereco = new EnderecoControle();
            ArrayList<Endereco> arrayEndereco = new ArrayList<>();
           for(int i=0; i < fornecedor.buscar().size(); i++){
            for (int j=0;j<endereco.busca().size();j++){
                    if(fornecedor.buscar().get(i).getCodigoEndereco()== endereco.busca().get(j).getCodigo()){
                            
                    arrayEndereco.add(endereco.busca().get(j));
              
                    }
                }
            }
            PdfWriter writer = new PdfWriter("RelatorioFornecedor.pdf");
            PdfDocument pdf = new PdfDocument(writer);           
            Document document = new Document(pdf);            
            document.setMargins(20, 20, 20, 20);
            PdfFont font = PdfFontFactory.createFont(FontConstants.TIMES_ROMAN);
            document.setFont(font);
            Paragraph cabecalho1 = new Paragraph("Lista de Fornecedores");
            document.add(cabecalho1);
            Table table = new Table(9);
            table.addCell(new Cell().add(new Paragraph("Codigo")));
            table.addCell(new Cell().add(new Paragraph("Nome")));
            table.addCell(new Cell().add(new Paragraph("CPF")));
            table.addCell(new Cell().add(new Paragraph("CNPJ")));
            table.addCell(new Cell().add(new Paragraph("Telefone")));
            table.addCell(new Cell().add(new Paragraph("Rua")));
            table.addCell(new Cell().add(new Paragraph("Numero")));
            table.addCell(new Cell().add(new Paragraph("Bairro")));
            table.addCell(new Cell().add(new Paragraph("Cidade")));
            for(int i=0;i<fornecedor.buscar().size();i++){                
                table.addCell(new Cell().add(new Paragraph(String.valueOf(fornecedor.buscar().get(i).getCodigo()))));
                table.addCell(new Cell().add(new Paragraph(fornecedor.buscar().get(i).getNomeFornecedor())));
                table.addCell(new Cell().add(new Paragraph(fornecedor.buscar().get(i).getCpfFornecedor())));
                table.addCell(new Cell().add(new Paragraph(fornecedor.buscar().get(i).getCnpjFornecedor())));
                table.addCell(new Cell().add(new Paragraph(fornecedor.buscar().get(i).getTelefone())));
                table.addCell(new Cell().add(new Paragraph(endereco.busca().get(i).getRua())));
                table.addCell(new Cell().add(new Paragraph(endereco.busca().get(i).getNumero())));
                table.addCell(new Cell().add(new Paragraph(endereco.busca().get(i).getBairro())));
                table.addCell(new Cell().add(new Paragraph(endereco.busca().get(i).getCidade())));
            }
            document.add(table);
            document.close();
            Desktop.getDesktop().open(new File("RelatorioFornecedor.pdf"));
        } catch (IOException ex) {
            Logger.getLogger(JfrmMenuGerente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmMenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmMenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmMenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmMenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmMenuGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuAlterarFuncionario;
    private javax.swing.JMenuItem jMenuBuscarFuncionario;
    private javax.swing.JMenuItem jMenuCadastrarFuncionario;
    private javax.swing.JMenuItem jMenuExcluirFuncionario;
    private javax.swing.JMenuItem jMenuGerarRelatorio;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JMenu jmnAddFuncionario;
    private javax.swing.JMenu jmnGerarRelatorio;
    private javax.swing.JMenuBar jmnMenu;
    private javax.swing.JMenu jmnSair;
    // End of variables declaration//GEN-END:variables
}
