/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controle.ProdutoControle;
import Modelo.Funcionario;
import Modelo.Produto;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leticia Ribeiro
 */
public class JfrmRealizaVenda extends javax.swing.JFrame {

    /**
     * Creates new form JfrmRealizarVenda
     */
    Funcionario funcionario = new Funcionario();
    public JfrmRealizaVenda() {
        initComponents();
    }
        public JfrmRealizaVenda(Funcionario funcionario) {
        initComponents();
         this.funcionario=funcionario;   
    }
    /*
       
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtxtProduto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblLista = new javax.swing.JTable();
        jbtnPesquisar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSoma = new javax.swing.JLabel();
        jbtnFinalizarCompra = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblPesquisa = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtQuantidade = new javax.swing.JTextField();
        jbtnSeta = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jAtualizar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Realizar Venda");

        jLabel1.setText("Produto");

        jtblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtblLista);

        jbtnPesquisar.setText("Pesquisar");
        jbtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPesquisarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Total:");

        jSoma.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jSoma.setText("R$ 0.0");

        jbtnFinalizarCompra.setText("Finalizar Compra");
        jbtnFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFinalizarCompraActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jtblPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jtblPesquisa);

        jLabel6.setText("Lista de Produtos");

        jLabel7.setText("Lista de Compras");

        jLabel8.setText("Quantidade");

        jtxtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtQuantidadeActionPerformed(evt);
            }
        });

        jbtnSeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Rounded_shift_right_arrow.png"))); // NOI18N
        jbtnSeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSetaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Dinheiro");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Cartão");

        jAtualizar.setText("Atualizar");
        jAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAtualizarActionPerformed(evt);
            }
        });

        jButton1.setText("Remover");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnFinalizarCompra)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnSeta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtQuantidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(8, 8, 8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(26, 26, 26)
                                        .addComponent(jtxtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtnPesquisar)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel6))
                                .addGap(200, 200, 200)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(455, 455, 455))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(489, 489, 489)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jAtualizar)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jbtnPesquisar))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnSeta)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jSoma)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAtualizar)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnFinalizarCompra)
                            .addComponent(jButton2))
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPesquisarActionPerformed
        // TODO add your handling code here:
        Produto produto = new Produto();
        produto.setNomeProduto(jtxtProduto.getText());
        ProdutoControle produtoControle = new ProdutoControle();
        DefaultTableModel modeloTabela = (DefaultTableModel)jtblPesquisa.getModel();
        modeloTabela = new DefaultTableModel(new String[] {"Nome do Produto", "Modelo", "Data de Validade", "Preço de Venda", "Quantidade"}, 0);
        ArrayList<Produto> array = produtoControle.buscar(produto.getNomeProduto());
        ArrayList<Float> arraycodigo = produtoControle.pegaQuantidade(produto.getNomeProduto());
        for(int i = 0; i < array.size();i++){
            Object[] data = {array.get(i).getNomeProduto(), array.get(i).getModelo(), array.get(i).getDataValidade(),  array.get(i).getPrecoVenda(), arraycodigo.get(i)};
            modeloTabela.addRow(data);
        }
        jtblPesquisa.setModel(modeloTabela);
        jtblPesquisa.getColumnModel().getColumn(0).setPreferredWidth(50);
        jtblPesquisa.getColumnModel().getColumn(1).setPreferredWidth(-10);
        jtblPesquisa.getColumnModel().getColumn(2).setPreferredWidth(50);
        jtblPesquisa.getColumnModel().getColumn(3).setPreferredWidth(50);
        jtblPesquisa.getColumnModel().getColumn(4).setPreferredWidth(30);        
    }//GEN-LAST:event_jbtnPesquisarActionPerformed

    private void jtxtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtQuantidadeActionPerformed
        ArrayList<Object> array = new ArrayList<>();
        float soma=0;
    private void jbtnSetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSetaActionPerformed
        // TODO add your handling code here:
        Produto produto = new Produto();
        produto.setNomeProduto(jtxtProduto.getText());
        DefaultTableModel modeloTabela = (DefaultTableModel)jtblLista.getModel();
        modeloTabela = new DefaultTableModel(new String[] {"Nome do Produto", "Modelo", "Data de Validade", "Preço de Venda", "Quantidade"}, 0);
        produto.setNomeProduto(jtblPesquisa.getValueAt(jtblPesquisa.getSelectedRow(), 0).toString());
        produto.setModelo(jtblPesquisa.getValueAt(jtblPesquisa.getSelectedRow(), 1).toString());
        produto.setDataValidade(jtblPesquisa.getValueAt(jtblPesquisa.getSelectedRow(), 2).toString());
        produto.setPrecoVenda((Float.parseFloat(jtblPesquisa.getValueAt(jtblPesquisa.getSelectedRow(), 3).toString())));
        Object[] data = {produto.getNomeProduto(), produto.getModelo(), produto.getDataValidade(),  produto.getPrecoVenda(), jtxtQuantidade.getText()};
        array.add(data);
        for(int i =0; i< array.size();i++){
            modeloTabela.addRow((Object[]) array.get(i));
        }
        jtblLista.setModel(modeloTabela);
        jtblLista.getColumnModel().getColumn(0).setPreferredWidth(50);
        jtblLista.getColumnModel().getColumn(1).setPreferredWidth(-10);
        jtblLista.getColumnModel().getColumn(2).setPreferredWidth(50);
        jtblLista.getColumnModel().getColumn(3).setPreferredWidth(50);
        jtblLista.getColumnModel().getColumn(4).setPreferredWidth(30);
        soma = 0;
        for(int i =0; i < jtblLista.getRowCount();i++){
            soma += Float.parseFloat(jtblLista.getValueAt(i, 3).toString())*Float.parseFloat(jtblLista.getValueAt(i, 4).toString());
        }
        jSoma.setText("R$ "+soma);
    }//GEN-LAST:event_jbtnSetaActionPerformed

    private void jbtnFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFinalizarCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnFinalizarCompraActionPerformed

    private void jAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAtualizarActionPerformed
        // TODO add your handling code here:
        soma = 0;
        for(int i =0; i < jtblLista.getRowCount();i++){
            soma += Float.parseFloat(jtblLista.getValueAt(i, 3).toString())*Float.parseFloat(jtblLista.getValueAt(i, 4).toString());
        }
        jSoma.setText("R$ "+soma);
        array.clear();
        for(int i =0;i < jtblLista.getRowCount();i++){
            Produto produto = new Produto();
            produto.setNomeProduto(jtblLista.getValueAt(i, 0).toString());
            produto.setModelo(jtblLista.getValueAt(i, 1).toString());
            produto.setDataValidade(jtblLista.getValueAt(i, 2).toString());
            produto.setPrecoVenda((Float.parseFloat(jtblLista.getValueAt(i, 3).toString())));
            array.add(produto);
        }
    }//GEN-LAST:event_jAtualizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel)jtblLista.getModel();
        soma -= Float.parseFloat(jtblLista.getValueAt(jtblLista.getSelectedRow(), 3).toString());
        array.remove(jtblLista.getSelectedRow());
        tableModel.removeRow(jtblLista.getSelectedRow());
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmRealizaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmRealizaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmRealizaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmRealizaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmRealizaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jAtualizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jSoma;
    private javax.swing.JButton jbtnFinalizarCompra;
    private javax.swing.JButton jbtnPesquisar;
    private javax.swing.JButton jbtnSeta;
    private javax.swing.JTable jtblLista;
    private javax.swing.JTable jtblPesquisa;
    private javax.swing.JTextField jtxtProduto;
    private javax.swing.JTextField jtxtQuantidade;
    // End of variables declaration//GEN-END:variables
}
