/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;

import Utilitarios.ConexaoBD;

/**
 *
 * @author Leticia Ribeiro
 */
public class JfrmMenuCaixa extends javax.swing.JFrame {

    /**
     * Creates new form JfrmMenuCaixa
     */
     ConexaoBD conecta = new ConexaoBD();
    public JfrmMenuCaixa() {
        initComponents();
        conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jmnMenu = new javax.swing.JMenuBar();
        jmnAddFuncionario = new javax.swing.JMenu();
        jmnRealizarVenda = new javax.swing.JCheckBoxMenuItem();
        jmnExcluirVenda = new javax.swing.JCheckBoxMenuItem();
        jmnBurcarVenda = new javax.swing.JCheckBoxMenuItem();
        jmnGerarRelatorio = new javax.swing.JMenu();
        jmnCadastrarProduto = new javax.swing.JCheckBoxMenuItem();
        jmnRemoverProduto = new javax.swing.JCheckBoxMenuItem();
        jmnBuscarProduto = new javax.swing.JCheckBoxMenuItem();
        jmnAlterarProduto = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmnCadastrarFornecedor = new javax.swing.JCheckBoxMenuItem();
        jmnRemoverFornecedor = new javax.swing.JCheckBoxMenuItem();
        jmnBuscarFornecedor = new javax.swing.JCheckBoxMenuItem();
        jmnAlterarFornecedor = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmnAddNotaFiscal = new javax.swing.JCheckBoxMenuItem();
        jmnBuscarNotaFiscal = new javax.swing.JCheckBoxMenuItem();
        jmnSais = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/carrinho.png"))); // NOI18N

        jmnAddFuncionario.setText("Vendas");

        jmnRealizarVenda.setSelected(true);
        jmnRealizarVenda.setText("Realizar Venda");
        jmnRealizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnRealizarVendaActionPerformed(evt);
            }
        });
        jmnAddFuncionario.add(jmnRealizarVenda);

        jmnExcluirVenda.setSelected(true);
        jmnExcluirVenda.setText("Excluir Venda");
        jmnExcluirVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnExcluirVendaActionPerformed(evt);
            }
        });
        jmnAddFuncionario.add(jmnExcluirVenda);

        jmnBurcarVenda.setSelected(true);
        jmnBurcarVenda.setText("Buscar Venda");
        jmnBurcarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnBurcarVendaActionPerformed(evt);
            }
        });
        jmnAddFuncionario.add(jmnBurcarVenda);

        jmnMenu.add(jmnAddFuncionario);

        jmnGerarRelatorio.setText("Produtos");

        jmnCadastrarProduto.setSelected(true);
        jmnCadastrarProduto.setText("Cadastrar Produto");
        jmnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnCadastrarProdutoActionPerformed(evt);
            }
        });
        jmnGerarRelatorio.add(jmnCadastrarProduto);

        jmnRemoverProduto.setSelected(true);
        jmnRemoverProduto.setText("Remover Produto");
        jmnRemoverProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnRemoverProdutoActionPerformed(evt);
            }
        });
        jmnGerarRelatorio.add(jmnRemoverProduto);

        jmnBuscarProduto.setSelected(true);
        jmnBuscarProduto.setText("Buscar Produto");
        jmnBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnBuscarProdutoActionPerformed(evt);
            }
        });
        jmnGerarRelatorio.add(jmnBuscarProduto);

        jmnAlterarProduto.setSelected(true);
        jmnAlterarProduto.setText("Alterar Produto");
        jmnAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnAlterarProdutoActionPerformed(evt);
            }
        });
        jmnGerarRelatorio.add(jmnAlterarProduto);

        jmnMenu.add(jmnGerarRelatorio);

        jMenu1.setText("Fornecedor");

        jmnCadastrarFornecedor.setSelected(true);
        jmnCadastrarFornecedor.setText("Cadastrar Fornecedor");
        jmnCadastrarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnCadastrarFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(jmnCadastrarFornecedor);

        jmnRemoverFornecedor.setSelected(true);
        jmnRemoverFornecedor.setText("Remover Fornecedor");
        jmnRemoverFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnRemoverFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(jmnRemoverFornecedor);

        jmnBuscarFornecedor.setSelected(true);
        jmnBuscarFornecedor.setText("Buscar Fornecedor");
        jmnBuscarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnBuscarFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(jmnBuscarFornecedor);

        jmnAlterarFornecedor.setSelected(true);
        jmnAlterarFornecedor.setText("Alterar Fornecedor");
        jmnAlterarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnAlterarFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(jmnAlterarFornecedor);

        jmnMenu.add(jMenu1);

        jMenu2.setText("Nota Fiscal");

        jmnAddNotaFiscal.setSelected(true);
        jmnAddNotaFiscal.setText("Adicionar Nota Fiscal");
        jmnAddNotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnAddNotaFiscalActionPerformed(evt);
            }
        });
        jMenu2.add(jmnAddNotaFiscal);

        jmnBuscarNotaFiscal.setSelected(true);
        jmnBuscarNotaFiscal.setText("Buscar Nota Fiscal");
        jmnBuscarNotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnBuscarNotaFiscalActionPerformed(evt);
            }
        });
        jMenu2.add(jmnBuscarNotaFiscal);

        jmnMenu.add(jMenu2);

        jmnSais.setText("Mais");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Sair");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jmnSais.add(jCheckBoxMenuItem2);

        jmnMenu.add(jmnSais);

        setJMenuBar(jmnMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(320, 243));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmnRealizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnRealizarVendaActionPerformed
        // TODO add your handling code here:
         JfrmFazerPedido tela =  new JfrmFazerPedido();
                   tela.setVisible(true);
    }//GEN-LAST:event_jmnRealizarVendaActionPerformed

    private void jmnExcluirVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnExcluirVendaActionPerformed
        // TODO add your handling code here:
         JfrmExcluirVenda tela =  new JfrmExcluirVenda();
                   tela.setVisible(true);
    }//GEN-LAST:event_jmnExcluirVendaActionPerformed

    private void jmnRemoverFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnRemoverFornecedorActionPerformed
        // TODO add your handling code here:
        JfrmRemoverFornecedor tela =  new JfrmRemoverFornecedor();
                   tela.setVisible(true);
    }//GEN-LAST:event_jmnRemoverFornecedorActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jmnBurcarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnBurcarVendaActionPerformed
        // TODO add your handling code here:
         JfrmBuscarVenda tela =  new JfrmBuscarVenda();
                   tela.setVisible(true);
    }//GEN-LAST:event_jmnBurcarVendaActionPerformed

    private void jmnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnCadastrarProdutoActionPerformed
        // TODO add your handling code here:
         JfrmCadastrarProduto tela =  new JfrmCadastrarProduto();
                   tela.setVisible(true);
    }//GEN-LAST:event_jmnCadastrarProdutoActionPerformed

    private void jmnRemoverProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnRemoverProdutoActionPerformed
        // TODO add your handling code here:
              JfrmRemoverProduto tela =  new JfrmRemoverProduto();
                   tela.setVisible(true);

    }//GEN-LAST:event_jmnRemoverProdutoActionPerformed

    private void jmnBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnBuscarProdutoActionPerformed
        // TODO add your handling code here:
        JfrmBuscarProduto tela =  new JfrmBuscarProduto();
                   tela.setVisible(true);
    }//GEN-LAST:event_jmnBuscarProdutoActionPerformed

    private void jmnAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnAlterarProdutoActionPerformed
        // TODO add your handling code here:
        JfrmAlterarProduto tela =  new JfrmAlterarProduto();
                   tela.setVisible(true);
    }//GEN-LAST:event_jmnAlterarProdutoActionPerformed

    private void jmnCadastrarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnCadastrarFornecedorActionPerformed
        // TODO add your handling code here:
        JfrmCadastrarFornecedor tela =  new JfrmCadastrarFornecedor();
                   tela.setVisible(true);
    }//GEN-LAST:event_jmnCadastrarFornecedorActionPerformed

    private void jmnBuscarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnBuscarFornecedorActionPerformed
        // TODO add your handling code here:
        JfrmBuscarFornecedor tela =  new JfrmBuscarFornecedor();
                   tela.setVisible(true);
    }//GEN-LAST:event_jmnBuscarFornecedorActionPerformed

    private void jmnAlterarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnAlterarFornecedorActionPerformed
        // TODO add your handling code here:
        JfrmAlterarFornecedor tela =  new JfrmAlterarFornecedor();
                   tela.setVisible(true);
    }//GEN-LAST:event_jmnAlterarFornecedorActionPerformed

    private void jmnAddNotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnAddNotaFiscalActionPerformed
        // TODO add your handling code here:
        JfrmAdcionarNotaFiscal tela =  new JfrmAdcionarNotaFiscal();
                   tela.setVisible(true);
    }//GEN-LAST:event_jmnAddNotaFiscalActionPerformed

    private void jmnBuscarNotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnBuscarNotaFiscalActionPerformed
        // TODO add your handling code here:
        JfrmBuscarNotaFiscal tela =  new JfrmBuscarNotaFiscal();
                   tela.setVisible(true);
    }//GEN-LAST:event_jmnBuscarNotaFiscalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmMenuCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmMenuCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmMenuCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmMenuCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmMenuCaixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jmnAddFuncionario;
    private javax.swing.JCheckBoxMenuItem jmnAddNotaFiscal;
    private javax.swing.JCheckBoxMenuItem jmnAlterarFornecedor;
    private javax.swing.JCheckBoxMenuItem jmnAlterarProduto;
    private javax.swing.JCheckBoxMenuItem jmnBurcarVenda;
    private javax.swing.JCheckBoxMenuItem jmnBuscarFornecedor;
    private javax.swing.JCheckBoxMenuItem jmnBuscarNotaFiscal;
    private javax.swing.JCheckBoxMenuItem jmnBuscarProduto;
    private javax.swing.JCheckBoxMenuItem jmnCadastrarFornecedor;
    private javax.swing.JCheckBoxMenuItem jmnCadastrarProduto;
    private javax.swing.JCheckBoxMenuItem jmnExcluirVenda;
    private javax.swing.JMenu jmnGerarRelatorio;
    private javax.swing.JMenuBar jmnMenu;
    private javax.swing.JCheckBoxMenuItem jmnRealizarVenda;
    private javax.swing.JCheckBoxMenuItem jmnRemoverFornecedor;
    private javax.swing.JCheckBoxMenuItem jmnRemoverProduto;
    private javax.swing.JMenu jmnSais;
    // End of variables declaration//GEN-END:variables
}
