/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;

import Utilitarios.ConexaoBD;

/**
 *
 * @author Leticia Ribeiro
 */
public class JfrmMenuGerente extends javax.swing.JFrame {

    /**
     * Creates new form JfrmMenuGerente
     */
     ConexaoBD conecta = new ConexaoBD();
    public JfrmMenuGerente() {
        initComponents();
        conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jmnMenu = new javax.swing.JMenuBar();
        jmnAddFuncionario = new javax.swing.JMenu();
        jMenuCadastrarFuncionario = new javax.swing.JMenuItem();
        jMenuExcluirFuncionario = new javax.swing.JMenuItem();
        jMenuBuscarFuncionario = new javax.swing.JMenuItem();
        jMenuAlterarFuncionario = new javax.swing.JMenuItem();
        jmnGerarRelatorio = new javax.swing.JMenu();
        jMenuGerarRelatorio = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jmnSais = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/manager_icon.png"))); // NOI18N

        jmnAddFuncionario.setText(" Funcionarios");

        jMenuCadastrarFuncionario.setText("Cadastrar Funcionário");
        jmnAddFuncionario.add(jMenuCadastrarFuncionario);

        jMenuExcluirFuncionario.setText("Excluir Funcionário");
        jmnAddFuncionario.add(jMenuExcluirFuncionario);

        jMenuBuscarFuncionario.setText("Buscar Funcionário");
        jmnAddFuncionario.add(jMenuBuscarFuncionario);

        jMenuAlterarFuncionario.setText("Alterar Funcionário");
        jmnAddFuncionario.add(jMenuAlterarFuncionario);

        jmnMenu.add(jmnAddFuncionario);

        jmnGerarRelatorio.setText("Relatórios");

        jMenuGerarRelatorio.setText("Gerar Relatório");
        jmnGerarRelatorio.add(jMenuGerarRelatorio);

        jMenuItem6.setText("Consultar Relatório");
        jmnGerarRelatorio.add(jMenuItem6);

        jmnMenu.add(jmnGerarRelatorio);

        jmnSais.setText("Mais");

        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jmnSais.add(jMenuSair);

        jmnMenu.add(jmnSais);

        setJMenuBar(jmnMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmMenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmMenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmMenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmMenuGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmMenuGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuAlterarFuncionario;
    private javax.swing.JMenuItem jMenuBuscarFuncionario;
    private javax.swing.JMenuItem jMenuCadastrarFuncionario;
    private javax.swing.JMenuItem jMenuExcluirFuncionario;
    private javax.swing.JMenuItem jMenuGerarRelatorio;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JMenu jmnAddFuncionario;
    private javax.swing.JMenu jmnGerarRelatorio;
    private javax.swing.JMenuBar jmnMenu;
    private javax.swing.JMenu jmnSais;
    // End of variables declaration//GEN-END:variables
}
